[build]
  command = "make build"           # Choose either "npm run build" or "make build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.19"

[context.production.environment]
  GO_VERSION = "1.19"
